[package]
name = "bnb_method_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplex_method = "0.1.1"
branch_bound_method = "0.1.1"
ndarray = "0.15.3"
log = "0.4.14"
env_logger = "0.9.0"
